# NodeJS for front-end tests
language: node_js
node_js: "7"

# Docker support
sudo: required
services:
    - docker

# Build all images
before_install:
    - src/docker/2.6/build.sh ckan
    - src/docker/2.6/build.sh ckan-cli
    - src/docker/2.6/build.sh ckan-dev
    - src/docker/2.6/build.sh ckan-production
    - src/docker/2.6/build.sh ckan-supervisor

# Install EasyCKAN
install:
    - curl -sSL https://raw.githubusercontent.com/thenets/Easy-CKAN/$TRAVIS_BRANCH/install_easyckan.sh | sudo bash
    - sudo easyckan install

# Front-end tests (check if server is working)
script:
    - src/docker/2.6/test.sh

# Notify
notifications:
  email: on_failure
  irc:
    - "chat.freenode.net#easyckan"